[package]
name = "pushy"
version = "0.0.0"
edition = "2021"
authors = ["João Marcos Bezerra <marcospb19@hotmail.com>"]
repository = "https://github.com/marcospb19/pushy"
license = "MIT"

[features]
default = ["std"]
std = []
